<?xml version="1.0" encoding="UTF-8"?>

<!-- == Provenance: YATC-shared/xsl/util/constants.xsl == -->
<!-- == Distribution: MP9-Medicatieproces-9.3.0; 1.0.10; 2025-04-16T18:06:20.52+02:00 == -->
<xsl:stylesheet exclude-result-prefixes="#all"
                version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:yatcs="https://nictiz.nl/ns/YATC-shared"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                xmlns:local="#local.2024032610445099691870100">
   <!-- ================================================================== -->
   <!--
         Contains any constants we might need. Anticipated are OIDs/URIs, ConceptMaps, ...
    -->
   <!-- ================================================================== -->
   <!--
        Copyright © Nictiz
        
        This program is free software; you can redistribute it and/or modify it under the terms of the
        GNU Lesser General Public License as published by the Free Software Foundation; either version
        2.1 of the License, or (at your option) any later version.
        
        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
        without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU Lesser General Public License for more details.
        
        The full text of the license is available at http://www.gnu.org/copyleft/lesser.html
    -->
   <!-- ================================================================== -->
   <!-- Some constants depend on the FHIR version used, so this parameter can be used to select either 'STU3' (default) or 'R4' -->
   <xsl:param name="fhirVersion"
              select="'STU3'"/>
   <xsl:variable name="maxLengthFHIRLogicalId"
                 select="64"
                 as="xs:integer"/>
   <xsl:variable name="ada-unit-second"
                 select="('seconde', 's', 'sec', 'second')"/>
   <xsl:variable name="ada-unit-minute"
                 select="('minuut', 'min', 'minute')"/>
   <xsl:variable name="ada-unit-hour"
                 select="('uur', 'h', 'hour')"/>
   <xsl:variable name="ada-unit-day"
                 select="('dag', 'd', 'day')"/>
   <xsl:variable name="ada-unit-week"
                 select="('week', 'wk')"/>
   <xsl:variable name="ada-unit-month"
                 select="('maand', 'mo', 'month')"/>
   <xsl:variable name="ada-unit-year"
                 select="('jaar', 'a', 'year')"/>
   <xsl:variable name="ada-unit-kilo"
                 select="('kilo', 'kg', 'kilogram')"/>
   <xsl:variable name="ada-unit-gram"
                 select="('gram', 'g', 'gr')"/>
   <xsl:variable name="ada-unit-cm"
                 select="('centimeter', 'cm')"/>
   <xsl:variable name="ada-unit-m"
                 select="('meter', 'm')"/>
   <xsl:variable name="ada-unit-liter"
                 select="('liter', 'l')"/>
   <xsl:variable name="ada-unit-dl"
                 select="('deciliter', 'dl')"/>
   <xsl:variable name="ada-unit-cl"
                 select="('centiliter', 'cl')"/>
   <xsl:variable name="ada-unit-ml"
                 select="('milliliter', 'ml')"/>
   <xsl:variable name="ada-unit-ul"
                 select="('microliter', 'ul')"/>
   <xsl:variable name="ada-unit-druppel"
                 select="('druppel', 'drp', '[drp]', 'druppels', 'drops')"/>
   <xsl:variable name="ada-unit-degrees"
                 select="('deg', 'degrees', 'graden')"/>
   <xsl:variable name="ada-unit-degrees-celsius"
                 select="('Cel', 'graden Celsius', 'graden celsius', 'degrees Celsius', 'degrees celsius', 'Celsius', 'celsius')"/>
   <xsl:variable name="ada-unit-pH"
                 select="('pH', '[pH]')"/>
   <xsl:variable name="ada-unit-mmol-l"
                 select="('mmol/L', 'mmol/l', 'mmol per liter')"/>
   <xsl:variable name="ada-unit-mmHg"
                 select="('mmHg', 'mm[Hg]')"/>
   <xsl:variable name="ada-unit-diopter"
                 select="('dpt', '[diop]', 'diopter', 'dioptrie')"/>
   <xsl:variable name="ada-unit-prism-diopter"
                 select="('PD', '[p''diop]', 'prism diopter', 'prisma dioptrie')"/>
   <xsl:variable name="oidAGB"
                 select="'2.16.840.1.113883.2.4.6.1'"/>
   <xsl:variable name="oidAGBSpecialismen"
                 select="'2.16.840.1.113883.2.4.6.7'"/>
   <xsl:variable name="oidAORTAApplicatieID"
                 select="'2.16.840.1.113883.2.4.6.6'"/>
   <xsl:variable name="oidAORTAProfileID"
                 select="'2.16.840.1.113883.2.4.3.11.1'"/>
   <xsl:variable name="oidATC"
                 select="'2.16.840.1.113883.6.73'"/>
   <xsl:variable name="oidBIGregister"
                 select="'2.16.528.1.1007.5.1'"/>
   <xsl:variable name="oidBurgerservicenummer"
                 select="'2.16.840.1.113883.2.4.6.3'"/>
   <xsl:variable name="oidChoiceListOrientation"
                 select="'2.16.840.1.113883.4.642.1.851'"/>
   <xsl:variable name="oidFHIRObservationCategory"
                 select="'2.16.840.1.113883.4.642.1.393'"/>
   <xsl:variable name="oidGStandaardGPK"
                 select="'2.16.840.1.113883.2.4.4.1'"/>
   <xsl:variable name="oidGStandaardPRK"
                 select="'2.16.840.1.113883.2.4.4.10'"/>
   <xsl:variable name="oidGStandaardHPK"
                 select="'2.16.840.1.113883.2.4.4.7'"/>
   <xsl:variable name="oidGStandaardSSK"
                 select="'2.16.840.1.113883.2.4.4.1.725'"/>
   <xsl:variable name="oidGStandaardSNK"
                 select="'2.16.840.1.113883.2.4.4.1.750'"/>
   <xsl:variable name="oidGStandaardTH122OngewensteGroepen"
                 select="'2.16.840.1.113883.2.4.4.1.902.122'"/>
   <xsl:variable name="oidGStandaardZInummer"
                 select="'2.16.840.1.113883.2.4.4.8'"/>
   <xsl:variable name="oidGStandaardTH007Toedieningswegen"
                 select="'2.16.840.1.113883.2.4.4.9'"/>
   <xsl:variable name="oidGStandaardBST361"
                 select="'2.16.840.1.113883.2.4.4.1.361'"/>
   <xsl:variable name="oidGStandaardBST902THES2"
                 select="'2.16.840.1.113883.2.4.4.1.900.2'"/>
   <xsl:variable name="oidGStandaardTH040ContraIndicaties"
                 select="'2.16.840.1.113883.2.4.4.1.902.40'"/>
   <xsl:variable name="oidGStandaardFarmaceutischeVormen"
                 select="'2.16.840.1.113883.2.4.4.11'"/>
   <xsl:variable name="oidGTIN"
                 select="'1.3.160'"/>
   <xsl:variable name="oidHIBC"
                 select="'2.16.840.1.113883.6.40'"/>
   <xsl:variable name="oidHL7AcknowledgementDetailCode"
                 select="'2.16.840.1.113883.5.1100'"/>
   <xsl:variable name="oidHL7ActCode"
                 select="'2.16.840.1.113883.5.4'"/>
   <xsl:variable name="oidHL7ActClass"
                 select="'2.16.840.1.113883.5.6'"/>
   <xsl:variable name="oidHL7ActStatus"
                 select="'2.16.840.1.113883.5.14'"/>
   <xsl:variable name="oidHL7ActReason"
                 select="'2.16.840.1.113883.5.8'"/>
   <xsl:variable name="oidHL7AddressUse"
                 select="'2.16.840.1.113883.5.1119'"/>
   <xsl:variable name="oidHL7AdministrativeGender"
                 select="'2.16.840.1.113883.5.1'"/>
   <xsl:variable name="oidHL7InteractionID"
                 select="'2.16.840.1.113883.1.6'"/>
   <xsl:variable name="oidHL7LanguageAbilityMode"
                 select="'2.16.840.1.113883.5.60'"/>
   <xsl:variable name="oidHL7LanguageAbilityProficiency"
                 select="'2.16.840.1.113883.5.61'"/>
   <xsl:variable name="oidHL7NullFlavor"
                 select="'2.16.840.1.113883.5.1008'"/>
   <xsl:variable name="oidHL7ObservationInterpretation"
                 select="'2.16.840.1.113883.5.83'"/>
   <xsl:variable name="oidHL7SpecimenType"
                 select="'2.16.840.1.113883.5.129'"/>
   <xsl:variable name="oidHL7ParticipationType"
                 select="'2.16.840.1.113883.5.90'"/>
   <xsl:variable name="oidHL7RoleCode"
                 select="'2.16.840.1.113883.5.111'"/>
   <xsl:variable name="oidISO3166"
                 select="'1.0.3166.1.2.2'"/>
   <xsl:variable name="oidHL7V3MaritalStatus"
                 select="'2.16.840.1.113883.5.2'"/>
   <xsl:variable name="oidICD10NL-STU3"
                 select="'1.2.276.0.76.5.409'"/>
   <xsl:variable name="oidICD10NL-R4"
                 select="'2.16.840.1.113883.6.3.2'"/>
   <xsl:variable name="oidICPC1NL"
                 select="'2.16.840.1.113883.2.4.4.31.1'"/>
   <xsl:variable name="oidJournaalregeltypen"
                 select="'2.16.840.1.113883.2.4.4.32.2'"/>
   <xsl:variable name="oidLOINC"
                 select="'2.16.840.1.113883.6.1'"/>
   <xsl:variable name="oidNHGTabel14Contactwijze"
                 select="'2.16.840.1.113883.2.4.4.30.14'"/>
   <xsl:variable name="oidNHGTabel15Verrichtingen"
                 select="'2.16.840.1.113883.2.4.4.30.15'"/>
   <xsl:variable name="oidNHGTabel25BCodesNumeriek"
                 select="'2.16.840.1.113883.2.4.4.5'"/>
   <xsl:variable name="oidNHGTabel45DiagnBepal"
                 select="'2.16.840.1.113883.2.4.4.30.45'"/>
   <xsl:variable name="oidNHGTabel45DiagnBepalResultaat"
                 select="'2.16.840.1.113883.2.4.4.30.1045'"/>
   <xsl:variable name="oidNHGTabel56Profylaxe"
                 select="'2.16.840.1.113883.2.4.4.30.56'"/>
   <xsl:variable name="oidNHGTabe361Gebruikseenheid"
                 select="'2.16.840.1.113883.2.4.4.1.361'"/>
   <xsl:variable name="oidQuestionnaireItemUIControlCodes"
                 select="'2.16.840.1.113883.4.642.1.849'"/>
   <xsl:variable name="oidQuestionnaireItemType"
                 select="'2.16.840.1.113883.4.642.1.438'"/>
   <xsl:variable name="oidQuestionnaireItemUsageMode"
                 select="'2.16.840.1.113883.4.642.1.855'"/>
   <xsl:variable name="oidQuestionnaireResponseStatus"
                 select="'2.16.840.1.113883.4.642.1.441'"/>
   <xsl:variable name="oidQuestionnaireTextCategories"
                 select="'2.16.840.1.113883.4.642.1.853'"/>
   <xsl:variable name="oidRoleCodeNLOrganizations"
                 select="'2.16.840.1.113883.2.4.15.1060'"/>
   <xsl:variable name="oidSNOMEDCT"
                 select="'2.16.840.1.113883.6.96'"/>
   <xsl:variable name="oidSBVZOrganization"
                 select="'2.16.528.1.1007'"/>
   <xsl:variable name="oidSBVZSystems"
                 select="'2.16.528.1.1007.4'"/>
   <xsl:variable name="oidUCUM"
                 select="'2.16.840.1.113883.6.8'"/>
   <xsl:variable name="oidURAOrganizations"
                 select="'2.16.528.1.1007.3.3'"/>
   <!-- http://www.oid-info.com/get/1.3.6.1.1.16 -->
   <xsl:variable name="oidUUID"
                 select="'1.3.6.1.1.16'"/>
   <xsl:variable name="oidVektisCOD472RolCode"
                 select="'2.16.840.1.113883.2.4.3.11.22.472'"/>
   <xsl:variable name="oidUZIPersons"
                 select="'2.16.528.1.1007.3.1'"/>
   <xsl:variable name="oidUZISystems"
                 select="'2.16.528.1.1007.3.2'"/>
   <xsl:variable name="oidUZIRoleCode"
                 select="'2.16.840.1.113883.2.4.15.111'"/>
   <xsl:variable name="oidUZOVI"
                 select="'2.16.840.1.113883.2.4.6.4'"/>
   <xsl:variable name="oidZIBNL-CM-CS"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4'"/>
   <xsl:variable name="oidZIBAanduidingBijNummer"
                 select="'2.16.840.1.113883.2.4.3.11.60.101.5.3'"/>
   <xsl:variable name="oidZIBGewichtContextKleding"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.8.1'"/>
   <xsl:variable name="oidZIBManchetType"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.15.1'"/>
   <xsl:variable name="oidZIBNaamgebruik"
                 select="'2.16.840.1.113883.2.4.3.11.60.101.5.4'"/>
   <xsl:variable name="oidZIBLaboratoriumUitslagTestUitslagStatus"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.16.1'"/>
   <xsl:variable name="oidZIBTelecomToestelTypes"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.22.1'"/>
   <xsl:variable name="oidZIBVerzekeringssoort"
                 select="'2.16.840.1.113883.2.4.3.11.60.101.5.1'"/>
   <xsl:variable name="oidZIBWilsverklaringType"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.14.1'"/>
   <xsl:variable name="oidZIBWoningType"
                 select="'2.16.840.1.113883.2.4.3.11.60.40.4.13.1'"/>
   <xsl:variable name="oidsGstandaardMedication"
                 as="xs:string*"
                 select="($oidGStandaardSSK, $oidGStandaardSNK, $oidGStandaardGPK, $oidGStandaardPRK, $oidGStandaardHPK, $oidGStandaardZInummer)"/>
   <!-- FHIR profile / extension naming -->
   <xsl:variable name="urlBaseNictizProfile"
                 select="'http://nictiz.nl/fhir/StructureDefinition/'"/>
   <xsl:variable name="urlExtAdministrationAgreementAdditionalInformation"
                 select="concat($urlBaseNictizProfile, 'ext-AdministrationAgreement.AdditionalInformation')"/>
   <xsl:variable name="urlExtAnatomicalLocationLaterality"
                 select="concat($urlBaseNictizProfile, 'ext-AnatomicalLocation.Laterality')"/>
   <xsl:variable name="urlExtAsAgreedIndicator"
                 select="concat($urlBaseNictizProfile, 'ext-AsAgreedIndicator')"/>
   <xsl:variable name="urlExtComment"
                 select="concat($urlBaseNictizProfile, 'ext-Comment')"/>
   <xsl:variable name="urlExtCommunicationPayloadContentCodeableConcept"
                 select="concat($urlBaseNictizProfile, 'ext-Communication.Payload.ContentCodeableConcept')"/>
   <xsl:variable name="urlExtContextEpisodeOfCare"
                 select="concat($urlBaseNictizProfile, 'ext-Context-EpisodeOfCare')"/>
   <xsl:variable name="urlExtCopyIndicator"
                 select="concat($urlBaseNictizProfile, 'ext-CopyIndicator')"/>
   <xsl:variable name="urlExtNLCodeSpecification"
                 select="concat($urlBaseNictizProfile, 'code-specification')"/>
   <xsl:variable name="urlExtNLMissingTypeReference"
                 select="concat($urlBaseNictizProfile, 'missing-type-reference')"/>
   <xsl:variable name="urlExtNLPractitionerRoleReference"
                 select="concat($urlBaseNictizProfile, 'practitionerrole-reference')"/>
   <xsl:variable name="urlExtHL7DataAbsentReason"
                 select="'http://hl7.org/fhir/StructureDefinition/data-absent-reason'"/>
   <xsl:variable name="urlExtHL7NullFlavor"
                 select="'http://hl7.org/fhir/StructureDefinition/iso21090-nullFlavor'"/>
   <xsl:variable name="urlExtIso21090ENqualifier"
                 select="'http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier'"/>
   <xsl:variable name="urlExtIso21090PQtranslation"
                 select="'http://hl7.org/fhir/StructureDefinition/iso21090-PQ-translation'"/>
   <xsl:variable name="urlExtMedicationAdministration2AgreedDateTime"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAdministration2.AgreedDateTime')"/>
   <xsl:variable name="urlExtMedicationAdministration2AgreedAmount"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAdministration2.AgreedAmount')"/>
   <xsl:variable name="urlExtMedicationAdministration2InjectionPatchSite"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAdministration2.InjectionPatchSite')"/>
   <xsl:variable name="urlExtMedicationAdministration2ReasonForDeviation"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAdministration2.ReasonForDeviation')"/>
   <xsl:variable name="urlExtMedicationAgreementAdditionalInformation"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAgreement.MedicationAgreementAdditionalInformation')"/>
   <xsl:variable name="urlExtMedicationAgreementNextPractitioner"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAgreement.NextPractitioner')"/>
   <xsl:variable name="urlExtMedicationAgreementPeriodOfUseCondition"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAgreement.PeriodOfUse.Condition')"/>
   <xsl:variable name="urlExtMedicationAgreementRelationMedicationUse"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationAgreement.RelationMedicationUse')"/>
   <xsl:variable name="urlExtMedicationHypersensitivityIdentifier"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationHypersensitivity.Identifier')"/>
   <xsl:variable name="urlExtMedicationMedicationDispenseDistributionForm"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationDispense.DistributionForm')"/>
   <xsl:variable name="urlExtMedicationUse2Prescriber"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationUse2.Prescriber')"/>
   <xsl:variable name="urlExtMedicationUseAuthor"
                 select="concat($urlBaseNictizProfile, 'ext-MedicationUse2.Author')"/>
   <xsl:variable name="urlExtPharmaceuticalTreatmentIdentifier"
                 select="concat($urlBaseNictizProfile, 'ext-PharmaceuticalTreatment.Identifier')"/>
   <xsl:variable name="urlExtRelationAdministrationAgreement"
                 select="concat($urlBaseNictizProfile, 'ext-RelationAdministrationAgreement')"/>
   <xsl:variable name="urlExtRepeatPeriodCyclical"
                 select="concat($urlBaseNictizProfile, 'zib-Medication-RepeatPeriodCyclicalSchedule')"/>
   <xsl:variable name="urlExtResourceCategory"
                 select="concat($urlBaseNictizProfile, 'ext-ResourceCategory')"/>
   <xsl:variable name="urlExtStoptype"
                 select="concat($urlBaseNictizProfile, 'ext-StopType')"/>
   <xsl:variable name="urlExtRegistrationDateTime"
                 select="concat($urlBaseNictizProfile, 'ext-RegistrationDateTime')"/>
   <!-- MP9 2.0.0-bèta version -->
   <xsl:variable name="urlExtTimeInterval-Period"
                 select="concat($urlBaseNictizProfile, 'ext-TimeInterval-Period')"/>
   <xsl:variable name="urlExtTimeInterval-Duration"
                 select="concat($urlBaseNictizProfile, 'ext-TimeInterval-Duration')"/>
   <!-- proper version -->
   <xsl:variable name="urlExtTimeIntervalPeriod"
                 select="concat($urlBaseNictizProfile, 'ext-TimeInterval.Period')"/>
   <xsl:variable name="urlExtTimeIntervalDuration"
                 select="concat($urlBaseNictizProfile, 'ext-TimeInterval.Duration')"/>
   <xsl:variable name="urlTimingExact"
                 select="'http://hl7.org/fhir/StructureDefinition/timing-exact'"/>
   <xsl:variable name="urlHL7CodeSystemDataAbsentReason"
                 select="'http://terminology.hl7.org/CodeSystem/data-absent-reason'"/>
   <xsl:variable name="NHGZoNodigNumeriek"
                 select="'1137'"/>
   <xsl:variable name="genderMap"
                 as="element()+">
      <map hl7Code="M"
           hl7CodeSystem="2.16.840.1.113883.5.1"
           fhirCode="male"
           displayName="man"
           displayNameEN="male"/>
      <map hl7Code="F"
           hl7CodeSystem="2.16.840.1.113883.5.1"
           fhirCode="female"
           displayName="vrouw"
           displayNameEN="female"/>
      <map hl7Code="UN"
           hl7CodeSystem="2.16.840.1.113883.5.1"
           fhirCode="other"
           displayName="ongedifferentieerd"
           displayNameEN="undifferentatiated"/>
      <map hl7Code="UNK"
           hl7CodeSystem="{$oidHL7NullFlavor}"
           fhirCode="unknown"
           displayName="onbekend"
           displayNameEN="unknown"/>
   </xsl:variable>
   <xsl:variable name="hl7NullFlavorMap"
                 as="element()+">
      <!-- bron: https://www.hl7.nl/wiki/index.php/Vocabulaire.NullFlavor -->
      <map hl7NullFlavor="NI"
           displayName="geen informatie"
           displayNameEN="no information"/>
      <map hl7NullFlavor="INV"
           displayName="ongeldig"
           displayNameEN="invalid"/>
      <map hl7NullFlavor="DER"
           displayName="afgeleid"
           displayNameEN="derived"/>
      <!-- er staat 'anders' in de bron, maar 'overig' is een logischere vertaling van other bij valuesets... -->
      <map hl7NullFlavor="OTH"
           displayName="overig"
           displayNameEN="other"/>
      <map hl7NullFlavor="NINF"
           displayName="negatief oneindig"
           displayNameEN="negative infinity"/>
      <map hl7NullFlavor="PINF"
           displayName="positief oneindig"
           displayNameEN="positive infinity"/>
      <map hl7NullFlavor="UNC"
           displayName="niet-gecodeerd"
           displayNameEN="unencoded"/>
      <map hl7NullFlavor="MSK"
           displayName="gemaskeerd"
           displayNameEN="masked"/>
      <map hl7NullFlavor="NA"
           displayName="niet van toepassing"
           displayNameEN="not applicable"/>
      <map hl7NullFlavor="UNK"
           displayName="onbekend"
           displayNameEN="unknown"/>
      <map hl7NullFlavor="ASKU"
           displayName="gevraagd maar onbekend"
           displayNameEN="asked but unknown"/>
      <map hl7NullFlavor="NAV"
           displayName="tijdelijk niet beschikbaar"
           displayNameEN="temporarily unavailable"/>
      <map hl7NullFlavor="NASK"
           displayName="niet gevraagd"
           displayNameEN="not asked"/>
      <!-- QS wordt gebruikt bij magistrale bereidingen: ingrediënten voor geneesmiddelen, betekent dan eigenlijk 'aanvullen tot' -->
      <map hl7NullFlavor="QS"
           displayName="voldoende hoeveelheid"
           displayNameEN="quantity sufficient"/>
      <map hl7NullFlavor="TRC"
           displayName="spoor"
           displayNameEN="trace"/>
   </xsl:variable>
   <xsl:variable name="hl7ActStatusMap"
                 as="element()+">
      <map hl7Code="active"
           hl7CodeSystem="{$oidHL7ActStatus}"
           displayName="actief"
           displayNameEN="active"/>
      <map hl7Code="suspended"
           hl7CodeSystem="{$oidHL7ActStatus}"
           displayName="onderbroken"
           displayNameEN="suspended"/>
      <map hl7Code="aborted"
           hl7CodeSystem="{$oidHL7ActStatus}"
           displayName="afgebroken"
           displayNameEN="aborted"/>
      <map hl7Code="completed"
           hl7CodeSystem="{$oidHL7ActStatus}"
           displayName="voltooid"
           displayNameEN="completed"/>
      <map hl7Code="cancelled"
           hl7CodeSystem="{$oidHL7ActStatus}"
           displayName="niet gestart"
           displayNameEN="cancelled"/>
   </xsl:variable>
   <xsl:variable name="zibLaboratoryResultStatusMap"
                 as="element()+">
      <map hl7Code="pending"
           hl7CodeSystem="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="Uitslag volgt"
           displayNameEN="Pending"/>
      <map hl7Code="preliminary"
           hl7CodeSystem="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="Voorlopig"
           displayNameEN="Preliminary"/>
      <map hl7Code="final"
           hl7CodeSystem="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="Definitief"
           displayNameEN="Final"/>
      <map hl7Code="appended"
           hl7CodeSystem="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="Aanvullend"
           displayNameEN="Appended"/>
      <map hl7Code="corrected"
           hl7CodeSystem="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="Gecorrigeerd"
           displayNameEN="Corrected"/>
   </xsl:variable>
   <xsl:variable name="zibLaboratoryTestResultStatusMap"
                 as="element()+">
      <xsl:copy-of select="$zibLaboratoryResultStatusMap"/>
   </xsl:variable>
   <xsl:variable name="uziRoleCodeMap"
                 as="element()+">
      <map hl7Code="01.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts"/>
      <map hl7Code="01.002"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Allergoloog (gesloten register)"/>
      <map hl7Code="01.003"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Anesthesioloog"/>
      <map hl7Code="01.004"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Apotheekhoudende huisarts"/>
      <map hl7Code="01.008"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Bedrijfsarts"/>
      <map hl7Code="01.010"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Cardioloog"/>
      <map hl7Code="01.011"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Cardiothoracaal chirurg"/>
      <map hl7Code="01.012"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Dermatoloog"/>
      <map hl7Code="01.013"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts v. maag-darm-leverziekten"/>
      <map hl7Code="01.014"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Chirurg"/>
      <map hl7Code="01.015"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Huisarts"/>
      <map hl7Code="01.016"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Internist"/>
      <map hl7Code="01.018"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Keel- neus- en oorarts"/>
      <map hl7Code="01.019"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Kinderarts"/>
      <map hl7Code="01.020"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts klinische chemie (gesloten register)"/>
      <map hl7Code="01.021"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch geneticus"/>
      <map hl7Code="01.022"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch geriater"/>
      <map hl7Code="01.023"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Longarts"/>
      <map hl7Code="01.024"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts-microbioloog"/>
      <map hl7Code="01.025"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Neurochirurg"/>
      <map hl7Code="01.026"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Neuroloog"/>
      <map hl7Code="01.030"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Nucleair geneeskundige"/>
      <map hl7Code="01.031"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Oogarts"/>
      <map hl7Code="01.032"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Orthopedisch chirurg"/>
      <map hl7Code="01.033"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Patholoog"/>
      <map hl7Code="01.034"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Plastisch chirurg"/>
      <map hl7Code="01.035"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Psychiater"/>
      <map hl7Code="01.039"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Radioloog"/>
      <map hl7Code="01.040"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Radiotherapeut"/>
      <map hl7Code="01.041"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Reumatoloog"/>
      <map hl7Code="01.042"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Revalidatiearts"/>
      <map hl7Code="01.045"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Uroloog"/>
      <map hl7Code="01.046"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Gynaecoloog"/>
      <map hl7Code="01.047"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Specialist ouderengeneeskunde"/>
      <map hl7Code="01.048"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verzekeringsarts"/>
      <map hl7Code="01.050"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Zenuwarts (gesloten register)"/>
      <map hl7Code="01.062"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Internist-Allergoloog (gesloten register)"/>
      <map hl7Code="01.055"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts maatschappij en gezondheid"/>
      <map hl7Code="01.056"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Arts voor verstandelijk gehandicapten"/>
      <map hl7Code="01.070"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Jeugdarts"/>
      <map hl7Code="01.071"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Spoedeisende hulp arts"/>
      <map hl7Code="01.074"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Sportarts"/>
      <map hl7Code="02.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Tandarts"/>
      <map hl7Code="02.053"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Orthodontist"/>
      <map hl7Code="02.054"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Kaakchirurg"/>
      <map hl7Code="03.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verloskundige"/>
      <map hl7Code="04.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Fysiotherapeut"/>
      <map hl7Code="16.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Psychotherapeut"/>
      <map hl7Code="17.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Apotheker"/>
      <map hl7Code="17.060"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Ziekenhuisapotheker"/>
      <map hl7Code="17.075"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Openbaar apotheker"/>
      <map hl7Code="25.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Gezondheidszorgpsycholoog"/>
      <map hl7Code="25.061"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch psycholoog"/>
      <map hl7Code="25.063"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch neuropsycholoog"/>
      <map hl7Code="30.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpleegkundige"/>
      <map hl7Code="30.065"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpl. spec. prev. zorg bij som. aandoeningen"/>
      <map hl7Code="30.066"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpl. spec. acute zorg bij som. aandoeningen"/>
      <map hl7Code="30.067"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpl. spec. intensieve zorg bij som. aandoeningen"/>
      <map hl7Code="30.068"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpl. spec. chronische zorg bij som. aandoeningen"/>
      <map hl7Code="30.069"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Verpl. spec. geestelijke gezondheidszorg"/>
      <map hl7Code="31.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Orthopedagoog-generalist"/>
      <map hl7Code="79.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Geregistreerd-mondhygiënist"/>
      <map hl7Code="80.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Bachelor medisch hulpverlener"/>
      <map hl7Code="81.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Physician assistant"/>
      <map hl7Code="82.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch technoloog"/>
      <map hl7Code="83.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Apothekersassistent"/>
      <map hl7Code="84.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Klinisch fysicus"/>
      <map hl7Code="85.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Tandprotheticus"/>
      <map hl7Code="86.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="VIG-er"/>
      <map hl7Code="87.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Optometrist"/>
      <map hl7Code="88.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Huidtherapeut"/>
      <map hl7Code="89.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Diëtist"/>
      <map hl7Code="90.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Ergotherapeut"/>
      <map hl7Code="91.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Logopedist"/>
      <map hl7Code="92.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Mondhygiënist"/>
      <map hl7Code="93.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Oefentherapeut Mensendieck"/>
      <map hl7Code="94.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Oefentherapeut Cesar"/>
      <map hl7Code="95.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Orthoptist"/>
      <map hl7Code="96.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Podotherapeut"/>
      <map hl7Code="97.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Radiodiagnistisch laborant"/>
      <map hl7Code="98.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Radiotherapeutisch laborant"/>
      <map hl7Code="99.000"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.111"
           displayName="Zorgverlener andere zorg"/>
   </xsl:variable>
   <xsl:variable name="orgRoleCodeMap"
                 as="element()+">
      <map hl7Code="V4"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Ziekenhuis"/>
      <map hl7Code="V5"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Universitair Medisch Centrum"/>
      <map hl7Code="V6"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Algemeen ziekenhuis"/>
      <map hl7Code="BRA"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Brandwondencentrum"/>
      <map hl7Code="Z4"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Zelfstandig behandelcentrum"/>
      <map hl7Code="Z5"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Diagnostisch centrum"/>
      <map hl7Code="B1"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Beeldvormende diagnostiek"/>
      <map hl7Code="B2"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Echocentrum"/>
      <map hl7Code="X3"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Verplegings- of verzorgingsinstelling"/>
      <map hl7Code="R5"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Verpleeghuis"/>
      <map hl7Code="M1"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Verzorgingstehuis"/>
      <map hl7Code="A1"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Apotheekinstelling"/>
      <map hl7Code="J8"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Openbare apotheek"/>
      <map hl7Code="K9"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Zelfstandig opererende ziekenhuisapotheek"/>
      <map hl7Code="H1"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Huisartsinstelling"/>
      <map hl7Code="Z3"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Huisartspraktijk (zelfstandig of groepspraktijk)"/>
      <map hl7Code="K3"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Apotheekhoudende huisartspraktijk"/>
      <map hl7Code="N6"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Huisartsenpost (t.b.v. dienstwaarneming)"/>
      <map hl7Code="L1"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Laboratorium"/>
      <map hl7Code="P4"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Polikliniek (als onderdeel van een ziekenhuis)"/>
      <map hl7Code="R8"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Revalidatiecentrum"/>
      <map hl7Code="P6"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Preventieve gezondheidszorg (waaronder Bevolkingsonderzoek)"/>
      <map hl7Code="G5"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Geestelijke Gezondheidszorg"/>
      <map hl7Code="G6"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Verstandelijk gehandicaptenzorg"/>
      <map hl7Code="T2"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Thuiszorg"/>
      <map hl7Code="K4"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Kraamzorg"/>
      <map hl7Code="H2"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Hospice"/>
      <map hl7Code="JGZ"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Jeugdgezondheidszorg"/>
      <map hl7Code="G3"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Verloskundigenpraktijk"/>
      <map hl7Code="GC"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Geboortecentrum"/>
      <map hl7Code="DIA"
           hl7CodeSystem="2.16.840.1.113883.2.4.15.1060"
           displayName="Dialysecentrum"/>
   </xsl:variable>
   <!-- 2022-09-07 oidAORTAApplicatieID Added on https://hl7.nl/wiki/index.php?title=OIDs_en_FHIR_System_URIs -->
   <xsl:variable name="oidMap"
                 as="element()+">
      <map oid="{$oidAGB}"
           uri="http://fhir.nl/fhir/NamingSystem/agb-z"
           displayName="AGB-Z"/>
      <map oid="{$oidAGBSpecialismen}"
           displayName="Vektis AGB-medische specialismen"/>
      <map oid="{$oidAORTAApplicatieID}"
           uri="http://fhir.nl/fhir/NamingSystem/aorta-app-id"
           displayName="AORTA ApplicatieID"/>
      <map oid="{$oidATC}"
           uri="http://www.whocc.no/atc"
           displayName="Anatomic Therapeutic Classification (ATC)"/>
      <map oid="{$oidBIGregister}"
           uri="http://fhir.nl/fhir/NamingSystem/big"
           displayName="BIG"/>
      <map oid="{$oidBurgerservicenummer}"
           uri="http://fhir.nl/fhir/NamingSystem/bsn"
           displayName="BSN"/>
      <map oid="{$oidGStandaardHPK}"
           displayName="G-Standaard HPK"/>
      <map oid="{$oidGStandaardPRK}"
           displayName="G-Standaard PRK"/>
      <map oid="{$oidGStandaardGPK}"
           displayName="G-Standaard GPK"/>
      <map oid="{$oidGStandaardSNK}"
           displayName="G-Standaard SNK"/>
      <map oid="{$oidGStandaardSSK}"
           displayName="G-Standaard SSK"/>
      <map oid="{$oidGStandaardZInummer}"
           displayName="G-Standaard ZI-nummer"/>
      <map oid="{$oidGStandaardTH007Toedieningswegen}"
           displayName="G-Standaard Toedieningswegen (tabel 7)"/>
      <map oid="{$oidGStandaardTH040ContraIndicaties}"
           displayName="G-Standaard TH040 Contraindicaties"/>
      <map oid="{$oidGStandaardTH122OngewensteGroepen}"
           displayName="G-Standaard TH122 Ongewenste groepen"/>
      <map oid="{$oidGStandaardBST361}"
           displayName="G-Standaard Bestand 361 a-tabel (eenheid gebruiksadvies)"/>
      <map oid="{$oidGStandaardBST902THES2}"
           displayName="G-Standaard thesaurus basiseenheden"/>
      <map oid="{$oidGStandaardFarmaceutischeVormen}"
           displayName="G-Standaard Farmaceutische vormen (tabel 6)"/>
      <map oid="{$oidGTIN}"
           uri="https://www.gs1.org/gtin"
           displayName="GS1 GTIN"/>
      <map oid="{$oidICD10NL-STU3}"
           uri="http://hl7.org/fhir/sid/icd-10-nl"
           displayName="ICD-10 NL"/>
      <map oid="{$oidICD10NL-R4}"
           uri="http://hl7.org/fhir/sid/icd-10-nl"
           displayName="ICD-10 NL"/>
      <map oid="{$oidICPC1NL}"
           uri="http://hl7.org/fhir/sid/icpc-1-nl"
           displayName="ICPC-1NL"/>
      <map oid="{$oidISO3166}"
           uri="urn:iso:std:iso:3166"
           displayName="ISO 3166-1 (alpha-2)"/>
      <map oid="{$oidJournaalregeltypen}"
           uri="http://fhir.nl/fhir/NamingSystem/journaalregeltypen"
           displayName="Journaalregeltypen"/>
      <map oid="{$oidLOINC}"
           uri="http://loinc.org"
           displayName="LOINC"/>
      <map oid="{$oidNHGTabel14Contactwijze}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-14-contactwijze"
           displayName="NHG Tabel 14 Contactwijze"/>
      <map oid="{$oidNHGTabel15Verrichtingen}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-15-verrichtingen"
           displayName="NHG Tabel 15 Verrichtingen"/>
      <map oid="{$oidNHGTabel25BCodesNumeriek}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-25-gebruiksvoorschrift#aanvullend-numeriek"
           displayName="NHG Tabel 25 B Codes (numeriek)"/>
      <map oid="{$oidNHGTabel45DiagnBepal}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-45-diagnostische-bepalingen"
           displayName="NHG Tabel 45 Diagnostische bepalingen"/>
      <map oid="{$oidNHGTabel45DiagnBepalResultaat}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-45-diagnostische-bepalingen#resultaten"
           displayName="NHG Labcodetabel 45 resultaten"/>
      <map oid="{$oidNHGTabel56Profylaxe}"
           uri="https://referentiemodel.nhg.org/tabellen/nhg-tabel-56-profylaxe-en-voorzorg"
           displayName="NHG Tabel 56 Profylaxe en voorzorg"/>
      <map oid="{$oidQuestionnaireItemUIControlCodes}"
           uri="http://hl7.org/fhir/questionnaire-item-control"
           displayName="Questionnaire Item UI Control Codes"/>
      <map oid="{$oidQuestionnaireItemType}"
           uri="http://hl7.org/fhir/item-type"
           displayName="QuestionnaireItemType"/>
      <map oid="{$oidQuestionnaireResponseStatus}"
           uri="http://hl7.org/fhir/questionnaire-answers-status"
           displayName="QuestionnaireResponseStatus"/>
      <map oid="{$oidQuestionnaireTextCategories}"
           uri="http://hl7.org/fhir/questionnaire-display-category"
           displayName="Questionnaire Text Categories"/>
      <map oid="{$oidRoleCodeNLOrganizations}"
           uri="http://nictiz.nl/fhir/NamingSystem/organization-type"
           displayName="HL7 RoleCodeNL Care provider type (organizations)"/>
      <map oid="{$oidSNOMEDCT}"
           uri="http://snomed.info/sct"
           displayName="SNOMED CT"/>
      <map oid="{$oidUCUM}"
           uri="http://unitsofmeasure.org"
           displayName="UCUM"/>
      <map oid="{$oidURAOrganizations}"
           uri="http://fhir.nl/fhir/NamingSystem/ura"
           displayName="URA"/>
      <map oid="{$oidUZIPersons}"
           uri="http://fhir.nl/fhir/NamingSystem/uzi-nr-pers"
           displayName="UZI Personen"/>
      <map oid="{$oidUZIRoleCode}"
           uri="http://fhir.nl/fhir/NamingSystem/uzi-rolcode"
           displayName="UZI Rolcodes"/>
      <map oid="{$oidUZISystems}"
           uri="http://fhir.nl/fhir/NamingSystem/uzi-nr-sys"
           displayName="UZI Systemen"/>
      <map oid="{$oidUZOVI}"
           uri="http://fhir.nl/fhir/NamingSystem/uzovi"
           displayName="UZOVI"/>
      <map oid="{$oidVektisCOD472RolCode}"
           displayName="Vektis Rolcode COD472-VEKT"/>
      <map oid="{$oidZIBAanduidingBijNummer}"
           displayName="ZIB AanduidingBijNummer"/>
      <map oid="{$oidZIBGewichtContextKleding}"
           displayName="ZIB ContextKleding"/>
      <map oid="{$oidZIBLaboratoriumUitslagTestUitslagStatus}"
           displayName="ZIB Laboratoriumuitslag Testuitslag ResultaatStatus"/>
      <map oid="{$oidZIBManchetType}"
           displayName="ZIB ManchetType"/>
      <map oid="{$oidZIBNaamgebruik}"
           displayName="ZIB Naamgebruik"/>
      <map oid="{$oidZIBNL-CM-CS}"
           displayName="ZIB NL-CM-CS Algemeen"/>
      <map oid="{$oidZIBTelecomToestelTypes}"
           displayName="ZIB Telecom ToestelTypes"/>
      <map oid="{$oidZIBVerzekeringssoort}"
           displayName="ZIB Verzekeringssoort"/>
      <map oid="{$oidZIBWilsverklaringType}"
           displayName="ZIB WilsverklaringType"/>
      <map oid="{$oidZIBWoningType}"
           displayName="ZIB WoningType"/>
      <xsl:choose>
         <xsl:when test="$fhirVersion = 'STU3'">
            <map oid="{$oidChoiceListOrientation}"
                 uri="http://hl7.org/fhir/choice-list-orientation"
                 displayName="ChoiceListOrientation"/>
            <map oid="{$oidFHIRObservationCategory}"
                 uri="http://hl7.org/fhir/observation-category"
                 displayName="ObservationCategory"/>
            <map oid="{$oidHL7ActCode}"
                 uri="http://hl7.org/fhir/v3/ActCode"
                 displayName="HL7 ActCode"/>
            <map oid="{$oidHL7ActStatus}"
                 uri="http://hl7.org/fhir/v3/ActStatus"
                 displayName="HL7 ActStatus"/>
            <map oid="{$oidHL7AcknowledgementDetailCode}"
                 uri="http://hl7.org/fhir/v3/AcknowledgementDetailCode"
                 displayName="HL7 AcknowledgementDetailCode"/>
            <map oid="{$oidHL7AdministrativeGender}"
                 uri="http://hl7.org/fhir/v3/AdministrativeGender"
                 displayName="HL7 AdministrativeGender"/>
            <map oid="{$oidHL7LanguageAbilityMode}"
                 uri="http://hl7.org/fhir/v3/LanguageAbilityMode"
                 displayName="HL7 LanguageAbilityMode"/>
            <map oid="{$oidHL7LanguageAbilityProficiency}"
                 uri="http://hl7.org/fhir/v3/LanguageAbilityProficiency"
                 displayName="HL7 LanguageAbilityProficiency"/>
            <map oid="{$oidHL7ObservationInterpretation}"
                 uri="http://hl7.org/fhir/v3/ObservationInterpretation"
                 displayName="HL7 ObservationInterpretation"/>
            <map oid="{$oidHL7SpecimenType}"
                 uri="http://hl7.org/fhir/v3/SpecimenType"
                 displayName="HL7 SpecimenType"/>
            <map oid="{$oidHL7ParticipationType}"
                 uri="http://hl7.org/fhir/v3/ParticipationType"
                 displayName="HL7 ParticipationType"/>
            <map oid="{$oidHL7NullFlavor}"
                 uri="http://hl7.org/fhir/v3/NullFlavor"
                 displayName="HL7 NullFlavor"/>
            <map oid="{$oidHL7AddressUse}"
                 uri="http://hl7.org/fhir/v3/AddressUse"
                 displayName="HL7 AddressUse"/>
            <map oid="{$oidHL7RoleCode}"
                 uri="http://hl7.org/fhir/v3/RoleCode"
                 displayName="HL7 RoleCode"/>
            <map oid="{$oidQuestionnaireItemUsageMode}"
                 uri="http://hl7.org/fhir/questionnaire-usage-mode"
                 displayName="QuestionnaireItemUsageMode Item UI Control Codes"/>
            <map uri="http://hl7.org/fhir/v2/0078"
                 displayName="HL7 Version 2 Table 0078 v2 Interpretation Codes"/>
            <map oid="{$oidHL7V3MaritalStatus}"
                 uri="http://hl7.org/fhir/v3/MaritalStatus"
                 displayName="HL7 MaritalStatus"/>
            <map oid="2.16.840.1.113883.5.1123"
                 uri="http://hl7.org/fhir/v3/DataOperation"
                 displayName="HL7 DataOperation"/>
            <map oid="2.16.840.1.113883.5.33 http://hl7.org/fhir/v3/DocumentCompletion"
                 displayName="HL7 DocumentCompletion"/>
         </xsl:when>
         <xsl:when test="$fhirVersion = 'R4'">
            <map oid="{$oidChoiceListOrientation}"
                 uri="http://terminology.hl7.org/CodeSystem/choice-list-orientation"
                 displayName="ChoiceListOrientation"/>
            <map oid="{$oidFHIRObservationCategory}"
                 uri="http://terminology.hl7.org/CodeSystem/observation-category"
                 displayName="ObservationCategory"/>
            <map oid="{$oidHL7ActCode}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-ActCode"
                 displayName="HL7 ActCode"/>
            <map oid="{$oidHL7ActStatus}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-ActStatus"
                 displayName="HL7 ActReason"/>
            <map oid="{$oidHL7ActReason}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-ActReason"
                 displayName="HL7 ActStatus"/>
            <map oid="{$oidHL7AcknowledgementDetailCode}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-AcknowledgementDetailCode"
                 displayName="HL7 AcknowledgementDetailCode"/>
            <map oid="{$oidHL7AdministrativeGender}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender"
                 displayName="HL7 AdministrativeGender"/>
            <map oid="{$oidHL7LanguageAbilityMode}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityMode"
                 displayName="HL7 LanguageAbilityMode"/>
            <map oid="{$oidHL7LanguageAbilityProficiency}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityProficiency"
                 displayName="HL7 LanguageAbilityProficiency"/>
            <map oid="{$oidHL7ObservationInterpretation}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
                 displayName="HL7 ObservationInterpretation"/>
            <map oid="{$oidHL7SpecimenType}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-SpecimenType"
                 displayName="HL7 SpecimenType"/>
            <map oid="{$oidHL7ParticipationType}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
                 displayName="HL7 ParticipationType"/>
            <map oid="{$oidHL7NullFlavor}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-NullFlavor"
                 displayName="HL7 NullFlavor"/>
            <map oid="{$oidHL7AddressUse}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-AddressUse"
                 displayName="HL7 AddressUse"/>
            <map oid="{$oidHL7RoleCode}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-RoleCode"
                 displayName="HL7 RoleCode"/>
            <map oid="{$oidHL7V3MaritalStatus}"
                 uri="http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"
                 displayName="HL7 MaritalStatus"/>
            <map oid="{$oidQuestionnaireItemUsageMode}"
                 uri="http://terminology.hl7.org/CodeSystem/questionnaire-usage-mode"
                 displayName="QuestionnaireItemUsageMode Item UI Control Codes"/>
            <map uri="http://terminology.hl7.org/CodeSystem/v2-0078"
                 displayName="HL7 Version 2 Table 0078 v2 Interpretation Codes"/>
            <map oid="2.16.840.1.113883.5.1123"
                 uri="http://terminology.hl7.org/CodeSystem/v3-DataOperation"
                 displayName="HL7 DataOperation"/>
            <map oid="2.16.840.1.113883.5.33"
                 uri="http://terminology.hl7.org/CodeSystem/v3-DocumentCompletion"
                 displayName="HL7 DocumentCompletion"/>
         </xsl:when>
      </xsl:choose>
   </xsl:variable>
   <!-- leniently recognize OID as OID even when nodes contain illegal leading zeroes -->
   <xsl:variable name="OIDpatternlenient"
                 select="'^[0-2](\.\d+)*$'"/>
   <!-- official OID pattern -->
   <xsl:variable name="OIDpattern"
                 select="'^[0-2](\.(0|[1-9]\d*))*$'"/>
   <!-- official UUID pattern -->
   <xsl:variable name="UUIDpattern"
                 select="'^[A-Fa-f\d]{8}-[A-Fa-f\d]{4}-[A-Fa-f\d]{4}-[A-Fa-f\d]{4}-[A-Fa-f\d]{12}$'"/>
   <!-- http://hl7.org/fhir/v3/ObservationInterpretation/cs.html -->
   <!-- https://zibs.nl/wiki/LaboratoryTestResult-v4.1(2017EN)#ResultFlagsCodelist -->
   <xsl:variable name="hl7v3ObservationInterpretation_to_zibInterpretatieVlaggen"
                 as="element(map)">
      <map>
         <!--<map inCode="(_GeneticObservationInterpretation)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="CAR" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="Carrier" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(_ObservationInterpretationChange)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="B" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="D" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="U" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="W" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(_ObservationInterpretationExceptions)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>-->
         <map inCode="&lt;"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="&gt;"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <!--<map inCode="AC" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="IE" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="QCF" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="TOX" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(_ObservationInterpretationNormality)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="A" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="AA" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>-->
         <map inCode="HH"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="LL"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="H"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="H&gt;"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="HH"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="HU"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="HH"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Above reference range"/>
         <map inCode="L"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="L&lt;"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="LL"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="LU"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <map inCode="LL"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Below reference range"/>
         <!--<map inCode="N" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(_ObservationInterpretationSusceptibility)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="IE" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>-->
         <map inCode="I"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="11896004"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Intermediate"/>
         <!--<map inCode="MS" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="NCL" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="NS" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>-->
         <map inCode="R"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="30714006"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Resistant"/>
         <map inCode="SYN-R"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="30714006"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Resistant"/>
         <map inCode="S"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="131196009"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Susceptible"/>
         <map inCode="SDD"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="131196009"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Susceptible"/>
         <map inCode="SYN-S"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="131196009"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Susceptible"/>
         <map inCode="VS"
              inCodeSystem="{$oidHL7ObservationInterpretation}"
              code="131196009"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Susceptible"/>
         <!--<map inCode="EX" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="HX" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="LX" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="HM" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(ObservationInterpretationDetection)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="IND" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="E" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="NEG" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="ND" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="POS" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="DET" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(ObservationInterpretationExpectation)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="EXP" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="UNE" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="OBX" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="(ReactivityObservationInterpretation)" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="NR" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="RR" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>
            <map inCode="WR" inCodeSystem="{$oidHL7ObservationInterpretation}" code="" codeSystem="{$oidSNOMEDCT}" displayName=""/>-->
      </map>
   </xsl:variable>
   <!-- https://zibs.nl/wiki/LaboratoryTestResult-v4.1(2017EN)#ResultFlagsCodelist -->
   <!-- http://hl7.org/fhir/v2/0078/index.html -->
   <xsl:variable name="zibInterpretatieVlaggen_to_hl7v2Table0078AbnormalFlags"
                 as="element(map)">
      <map>
         <!-- Above reference range || Boven referentiewaarde -->
         <map inCode="281302008"
              inCodeSystem="{$oidSNOMEDCT}"
              code="H"
              codeSystem="http://hl7.org/fhir/v2/0078"
              displayName="High"/>
         <!--Below reference range || Onder referentiewaarde-->
         <map inCode="281300000"
              inCodeSystem="{$oidSNOMEDCT}"
              code="L"
              codeSystem="http://hl7.org/fhir/v2/0078"
              displayName="Low"/>
         <!--Intermediate || Intermediair-->
         <map inCode="11896004"
              inCodeSystem="{$oidSNOMEDCT}"
              code="I"
              codeSystem="http://hl7.org/fhir/v2/0078"
              displayName="Intermediate"/>
         <!--Resistant || Resistent-->
         <map inCode="30714006"
              inCodeSystem="{$oidSNOMEDCT}"
              code="R"
              codeSystem="http://hl7.org/fhir/v2/0078"
              displayName="Resistant"/>
         <!--Susceptible || Sensitief-->
         <map inCode="131196009"
              inCodeSystem="{$oidSNOMEDCT}"
              code="S"
              codeSystem="http://hl7.org/fhir/v2/0078"
              displayName="Susceptible"/>
      </map>
   </xsl:variable>
   <!-- https://zibs.nl/wiki/LaboratoriumUitslag-v4.6(2020NL)#InterpretatieVlaggenCodelijst -->
   <!-- http://hl7.org/fhir/R4/valueset-observation-interpretation.html -->
   <xsl:variable name="zibInterpretatieVlaggen_to_fhirObservationInterpretation"
                 as="element(map)">
      <map>
         <!-- Above reference range || Boven referentiewaarde -->
         <map inCode="281302008"
              inCodeSystem="{$oidSNOMEDCT}"
              code="H"
              codeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              displayName="High"/>
         <!--Below reference range || Onder referentiewaarde-->
         <map inCode="281300000"
              inCodeSystem="{$oidSNOMEDCT}"
              code="L"
              codeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              displayName="Low"/>
         <!--Intermediate || Intermediair-->
         <map inCode="11896004"
              inCodeSystem="{$oidSNOMEDCT}"
              code="I"
              codeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              displayName="Intermediate"/>
         <!--Resistant || Resistent-->
         <map inCode="30714006"
              inCodeSystem="{$oidSNOMEDCT}"
              code="R"
              codeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              displayName="Resistant"/>
         <!--Susceptible || Sensitief-->
         <map inCode="131196009"
              inCodeSystem="{$oidSNOMEDCT}"
              code="S"
              codeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              displayName="Susceptible"/>
      </map>
   </xsl:variable>
   <!-- https://zibs.nl/wiki/LaboratoriumUitslag-v4.6(2020NL)#InterpretatieVlaggenCodelijst -->
   <!-- http://hl7.org/fhir/R4/valueset-observation-interpretation.html -->
   <xsl:variable name="fhirObservationInterpretation_to_zibInterpretatieVlaggen"
                 as="element(map)">
      <map>
         <!-- Above reference range || Boven referentiewaarde -->
         <map inCode="H"
              inCodeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              code="281302008"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Boven referentiewaarde"/>
         <!--Below reference range || Onder referentiewaarde-->
         <map inCode="L"
              inCodeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              code="281300000"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Onder referentiewaarde"/>
         <!--Intermediate || Intermediair-->
         <map inCode="I"
              inCodeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              code="11896004"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Intermediair"/>
         <!--Resistant || Resistent-->
         <map inCode="R"
              inCodeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              code="30714006"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Resistent"/>
         <!--Susceptible || Sensitief-->
         <map inCode="S"
              inCodeSystem="http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
              code="131196009"
              codeSystem="{$oidSNOMEDCT}"
              displayName="Sensitief"/>
      </map>
   </xsl:variable>
   <!-- http://hl7.org/fhir/R4/codesystem-data-absent-reason.html -->
   <!-- https://terminology.hl7.org/CodeSystem-v3-NullFlavor.html -->
   <!-- http://hl7.org/fhir/R4/cm-data-absent-reason-v3.html -->
   <xsl:variable name="fhirDataAbsentReason_to_NullFlavor">
      <map>
         <map inCode="unknown"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="UNK"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="onbekend"/>
         <map inCode="asked-unknown"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="ASKU"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Asked But Unknown"/>
         <map inCode="temp-unknown"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NAV"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Temporarily Unknown"/>
         <map inCode="not-asked"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NASK"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Not Asked"/>
         <!-- not in ConceptMap -->
         <map inCode="asked-declined"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="MSK"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Asked But Declined"/>
         <map inCode="masked"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="MSK"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Masked"/>
         <map inCode="not-applicable"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NA"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Not Applicable"/>
         <!-- not in ConceptMap -->
         <map inCode="unsupported"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NI"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Unsupported"/>
         <!-- not in ConceptMap -->
         <map inCode="as-text"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="OTH"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="As Text"/>
         <!-- not in ConceptMap -->
         <map inCode="error"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NI"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Error"/>
         <!-- not in ConceptMap -->
         <map inCode="not-a-number"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="INV"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Not a Number (NaN)"/>
         <map inCode="negative-infinity"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NINF"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Negative Infinity (NINF)"/>
         <map inCode="positive-infinity"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="PINF"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Positive Infinity (PINF)"/>
         <!-- not in ConceptMap -->
         <map inCode="not-performed"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="NI"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Not Performed"/>
         <map inCode="not-permitted"
              inCodeSystem="{$urlHL7CodeSystemDataAbsentReason}"
              code="OTH"
              codeSystem="{$oidHL7NullFlavor}"
              displayName="Not Permitted"/>
      </map>
   </xsl:variable>
   <!-- mp constants -->
   <xsl:variable name="daypartMap"
                 as="element()+">
      <map dayPart="night"
           fhirWhen="NIGHT"
           hl7PIVLPhaseLow="1970010100"
           hl7PIVLPhaseHigh="1970010106"
           code="2546009"
           codeSystem="{$oidSNOMEDCT}"
           displayName="'s nachts"
           codeSystemName="SNOMED CT"/>
      <map dayPart="morning"
           fhirWhen="MORN"
           hl7PIVLPhaseLow="1970010106"
           hl7PIVLPhaseHigh="1970010112"
           code="73775008"
           codeSystem="{$oidSNOMEDCT}"
           displayName="'s ochtends"
           codeSystemName="SNOMED CT"/>
      <map dayPart="afternoon"
           fhirWhen="AFT"
           hl7PIVLPhaseLow="1970010112"
           hl7PIVLPhaseHigh="1970010118"
           code="255213009"
           codeSystem="{$oidSNOMEDCT}"
           displayName="'s middags"
           codeSystemName="SNOMED CT"/>
      <map dayPart="evening"
           fhirWhen="EVE"
           hl7PIVLPhaseLow="1970010118"
           hl7PIVLPhaseHigh="1970010200"
           code="3157002"
           codeSystem="{$oidSNOMEDCT}"
           displayName="'s avonds"
           codeSystemName="SNOMED CT"/>
   </xsl:variable>
   <xsl:variable name="weekdayMap"
                 as="element()+">
      <map dayOfWeek="1"
           weekday="monday"
           fhirDayOfWeek="mon"
           hl7PIVLPhaseLow="19700601"
           code="307145004"
           codeSystem="{$oidSNOMEDCT}"
           displayName="maandag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="2"
           weekday="tuesday"
           fhirDayOfWeek="tue"
           hl7PIVLPhaseLow="19700602"
           code="307147007"
           codeSystem="{$oidSNOMEDCT}"
           displayName="dinsdag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="3"
           weekday="wednesday"
           fhirDayOfWeek="wed"
           hl7PIVLPhaseLow="19700603"
           code="307148002"
           codeSystem="{$oidSNOMEDCT}"
           displayName="woensdag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="4"
           weekday="thursday"
           fhirDayOfWeek="thu"
           hl7PIVLPhaseLow="19700604"
           code="307149005"
           codeSystem="{$oidSNOMEDCT}"
           displayName="donderdag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="5"
           weekday="friday"
           fhirDayOfWeek="fri"
           hl7PIVLPhaseLow="19700605"
           code="307150005"
           codeSystem="{$oidSNOMEDCT}"
           displayName="vrijdag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="6"
           weekday="saturday"
           fhirDayOfWeek="sat"
           hl7PIVLPhaseLow="19700606"
           code="307151009"
           codeSystem="{$oidSNOMEDCT}"
           displayName="zaterdag"
           codeSystemName="SNOMED CT"/>
      <map dayOfWeek="0"
           weekday="sunday"
           fhirDayOfWeek="sun"
           hl7PIVLPhaseLow="19700607"
           code="307146003"
           codeSystem="{$oidSNOMEDCT}"
           displayName="zondag"
           codeSystemName="SNOMED CT"/>
   </xsl:variable>
   <!-- checks https://hl7.org/fhir/R4/references.html#regex -->
   <xsl:variable name="restRegexR4"
                 as="xs:string"
                 select="'((http|https)://([A-Za-z0-9\-\\\.:%\$]*/)+)?(Account|ActivityDefinition|AdverseEvent|AllergyIntolerance|Appointment|AppointmentResponse|AuditEvent|Basic|Binary|BiologicallyDerivedProduct|BodyStructure|Bundle|CapabilityStatement|CarePlan|CareTeam|CatalogEntry|ChargeItem|ChargeItemDefinition|Claim|ClaimResponse|ClinicalImpression|CodeSystem|Communication|CommunicationRequest|CompartmentDefinition|Composition|ConceptMap|Condition|Consent|Contract|Coverage|CoverageEligibilityRequest|CoverageEligibilityResponse|DetectedIssue|Device|DeviceDefinition|DeviceMetric|DeviceRequest|DeviceUseStatement|DiagnosticReport|DocumentManifest|DocumentReference|EffectEvidenceSynthesis|Encounter|Endpoint|EnrollmentRequest|EnrollmentResponse|EpisodeOfCare|EventDefinition|Evidence|EvidenceVariable|ExampleScenario|ExplanationOfBenefit|FamilyMemberHistory|Flag|Goal|GraphDefinition|Group|GuidanceResponse|HealthcareService|ImagingStudy|Immunization|ImmunizationEvaluation|ImmunizationRecommendation|ImplementationGuide|InsurancePlan|Invoice|Library|Linkage|List|Location|Measure|MeasureReport|Media|Medication|MedicationAdministration|MedicationDispense|MedicationKnowledge|MedicationRequest|MedicationStatement|MedicinalProduct|MedicinalProductAuthorization|MedicinalProductContraindication|MedicinalProductIndication|MedicinalProductIngredient|MedicinalProductInteraction|MedicinalProductManufactured|MedicinalProductPackaged|MedicinalProductPharmaceutical|MedicinalProductUndesirableEffect|MessageDefinition|MessageHeader|MolecularSequence|NamingSystem|NutritionOrder|Observation|ObservationDefinition|OperationDefinition|OperationOutcome|Organization|OrganizationAffiliation|Patient|PaymentNotice|PaymentReconciliation|Person|PlanDefinition|Practitioner|PractitionerRole|Procedure|Provenance|Questionnaire|QuestionnaireResponse|RelatedPerson|RequestGroup|ResearchDefinition|ResearchElementDefinition|ResearchStudy|ResearchSubject|RiskAssessment|RiskEvidenceSynthesis|Schedule|SearchParameter|ServiceRequest|Slot|Specimen|SpecimenDefinition|StructureDefinition|StructureMap|Subscription|Substance|SubstanceNucleicAcid|SubstancePolymer|SubstanceProtein|SubstanceReferenceInformation|SubstanceSourceMaterial|SubstanceSpecification|SupplyDelivery|SupplyRequest|Task|TerminologyCapabilities|TestReport|TestScript|ValueSet|VerificationResult|VisionPrescription)/[A-Za-z0-9\-\.]{1,64}(/_history/[A-Za-z0-9\-\.]{1,64})?'"/>
</xsl:stylesheet>